Update read_json_files with filename and other error context
The current Generate HTML CI job returns the following error when a course participant's JSON file fails to load using the json.load function:

'''
ERROR: Exception: Expecting property name enclosed in double quotes: line 5 column 1 (char 97)
'''

This lacks some clarifying details, which are provided by other errors in this function.